version: 1
title: Reviewing Pull Requests
tagline: Start collaborating for GitHub, with GitHub.
description: Learn how GitHub uses pull request reviews to communicate and collaborate during the development process.
tags: [
  "GitHub", "Pull Requests"
]
template:
  name: "reviewing-pull-requests"
  url: "https://github.com/githubtraining/review-pull-requests-template"
before:
  - type: updateBranchProtection
    branch: master
    required_status_checks: null
    enforce_admins: true
    required_pull_request_reviews:
      include_admins: true
    restrictions: null
  - type: createIssue
    title: Welcome
    body: 01_intro.md
steps:
  - title: Assign Yourself
    description: Assign yourself to the first issue in this repository
    event: issues.assigned
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/issues/1
    actions:
      - type: gate
        left: "%payload.assignee.login%"
        operator: "==="
        right: "%user.username%"
      - type: respond
        with: 02_close-first-issue.md
      - type: createPullRequest
        title: Update Game Instructions
        with: 02_review-101.md
        head: game-instructions

  - title: Comment on a pull request
    description: Comment on the pull request opened in your repository.
    event: issue_comment.created
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/pull/2
    actions:
      - type: gate
        # TODO check this, make sure that user has commented, saying just about anything
        left: '%payload.comment.body%'
      - type: respond
        with: 03_successful-comment.md

  - title: Approve a pull request
    description: Approve the pull request so that it can be merged.
    event: pull_request_review.submitted
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/pull/2
    actions:
      - type: gate
        left: '%payload.review.state%'
        operator: ===
        right: APPROVED
      - type: mergeBranch
        head: game-instructions
      - type: respond
        with: 04_merging-pull-request.md
      - type: createPullRequest
        title: Change Tetris Colors
        with: 04_requiring-changes.md
        head: update-colors

  - title: Requesting Changes
    description: Leave a review that is requesting changes.
    event: pull_request_review.submitted
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/pull/3
    actions:
      - type: gate
        # TODO make sure they actually respond with request for changes
        # TODO if they generally comment
        - type: respond
          with: 05_general-comment.md
        # TODO if they approve
        - type: respond
          with: 05_approval.md
        # TODO if they request changes
        - type: respond
          with: 05_changes-requested.md
      - type: # TODO change the branch in the pull request to reflect the requested changes

  - title: Approve another pull request
    description: Approve the pull request that has been changed
    event: pull_request_review.submitted
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/pull/3
    actions:
      - type: gate # TODO check to make sure it's been approved
      - type: respond
        with: 06_thanks-for-approval.md
      - type: mergePullRequest
      - type: createIssue
        title: The Final Review
        with: 06_final-flow.md
        data:
          url: 'https://%user.username%.github.io/%payload.repository.name%'

  - title: Request a reviewer
    description: Create a new pull request, and request that the Lab Bot reviews it.
    event: pull_request.review_requested
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/pull/5
    actions:
      - type: gate
        # TODO check, make sure user creates pull request, and has lab bot assigned as reviewer
        left: "%payload.assignee.login%"
        operator: "==="
        right: "github-learning-lab"
      - type: createReview
        body: 07_approve-pr.md
        event: APPROVE
      - type: closeIssue
        with: 07_close-issue.md
        data:
          # TODO check if URL below is correct
          url: '%actions.issue.data.html_url%'

  - title: Merge pull request
    description: Merge the pull request once I've approved it.
    event: pull_request.closed
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/pull/5
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
      - type: respond
        with: 08_comment-final-pr.md
      - type: createIssue
        title: You did it!
        with: 08_final-issue.md
