title: Reviewing pull requests
tagline: Improve your collaboration on GitHub with pull request reviews.
description: See how collaboration works on GitHub and start building great things, together.
template:
    name: reviewing-a-pull-request
    repo: reviewing-a-pull-request-template
before:
  - type: updateBranchProtection
  - type: createIssue
    title: Welcome
    body: 01_intro.md
steps:
  - title: Assign Yourself
    description: Assign yourself to the first issue in this repository
    event: issues.assigned
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: gate
        left: '%payload.assignee.login%'
        operator: ===
        right: '%user.username%'
      - type: createPullRequest
        title: Update Game Instructions
        body: 02_review-101.md
        head: game-instructions
        action_id: pr2
      - type: respond
        with: 02_close-first-issue.md
        data:
          url: '%actions.pr2.data.html_url%'
      - type: closeIssue
        issue: Welcome

  - title: Comment on a pull request
    description: Comment on the pull request opened in your repository
    event: pull_request_review.submitted
    link: '{{ repoUrl }}/pull/2'
    actions:
      - type: gate
        every: true
        gates:
          - left: '%payload.review.state%'
            operator: ===
            right: 'commented'
          - left: '%payload.pull_request.title%'
            operator: ===
            right: Update Game Instructions
        else:
          - type: respond
            with: error.md
      - type: respond
        with: 03_successful-comment.md

  - title: Approve a pull request
    description: Approve the pull request so that it can be merged
    event: pull_request_review.submitted
    link: '{{ repoUrl }}/pull/2'
    actions:
      - type: gate
        left: '%payload.review.state%'
        operator: ===
        right: 'approved'
      - type: mergeBranch
        head: game-instructions
      - type: octokit
        method: gitdata.deleteReference
        owner: '%payload.repository.owner.login%'
        repo: '%payload.repository.name%'
        ref: heads/game-instructions
      - type: createPullRequest
        title: Change Tetris Colors
        body: 04_requesting-changes.md
        head: update-colors
        action_id: pr3
      - type: respond
        with: 04_merging-pull-request.md
        data:
          url: '%actions.pr3.data.html_url%'

  - title: Requesting Changes
    description: Leave a review that is requesting changes
    event: pull_request_review.submitted
    link: '{{ repoUrl }}/pull/3'
    actions:
      - type: gate
        left: '%payload.review.state%'
        operator: ===
        right: 'changes_requested'
        else:
        - type: gate
          gates:
            - left: '%payload.review.state'
              operator: ===
              right: COMMENT
            - type: respond
              with: 05_general-comment.md
            - left: '%payload.review.state'
              operator: ===
              right: APPROVE
            - type: respond
              with: 05_approval.md
      - type: mergeBranch
        head: add-multiple-colors
        base: update-colors
      - type: octokit
        method: gitdata.deleteReference
        owner: '%payload.repository.owner.login%'
        repo: '%payload.repository.name%'
        ref: heads/add-multiple-colors
      - type: respond
        with: 05_changes-requested.md

  - title: Approve another pull request
    description: Approve the pull request that has been changed
    event: pull_request_review.submitted
    link: '{{ repoUrl }}/pull/3'
    actions:
      - type: gate
        left: '%payload.review.state%'
        operator: ===
        right: 'approved'
      - type: mergePullRequest
      - type: octokit
        method: gitdata.deleteReference
        owner: '%payload.repository.owner.login%'
        repo: '%payload.repository.name%'
        ref: heads/update-colors
      - type: respond
        with: 08-suggest.md
        data:
          url: '%payload.repository.html_url%/compare/update-readme?expand=1'

  - title: Open a pull request from readme-update
    description: Do it
    event: pull_request.opened
    link: '{{ repoUrl }}/compare/readme-update?expand=1'
    actions:
      - type: octokit
        method: pullRequests.createComment
        owner: '%payload.repository.owner.login%'
        repo: '%payload.repository.name%'
        number: '%payload.pull_request.number%'
        path: README.md
        body: | 
          Thanks for opening this pull request, @%user.username%.
          I've made a suggested change to this pull request because I think you should link your version of the game in your README file. I made this suggestion by creating a review comment that uses some :sparkle: special :sparkle: formatting.
          It looks like this:

              ```suggestion
              You can play the game at: https://%user.username%.github.io/github-games/
              ```

          For more information about suggest changes, check out this [GitHub Help](https://help.github.com/articles/incorporating-feedback-in-your-pull-request) article.

          ```suggestion
          You can play the game [here](https://%user.username%.github.io/github-games/)
          ```
        commit_id: '%payload.pull_request.head.sha%'
        position: 1

  - title: Apply the suggestion
    description: Do it
    event: pull_request.synchronize
    link: '{{ repoUrl }}/pulls'
    actions:
      - type: createReview
        event: APPROVE
        body: 08-suggest-merge.md

  - title: Merge that PR
    description: Do it
    event: pull_request.closed
    link: '{{ repoUrl }}/pulls'
    actions:
      - type: gate
        left: pull_request.merged
      - type: respond
        with: 06-final-flow.md

  - title: Request a reviewer
    description: Create a new pull request, and request that the Lab Bot reviews it.
    event: pull_request.opened
    link: '{{ repoUrl }}/pull/5'
    actions:
      - type: createReview
        body: 07_approve-pr.md
        event: APPROVE
      - type: closeIssue
        issue: The Final Review
      - type: respond
        issue: The Final Review
        with: 07_close-issue.md
        data:
          url: '%actions.issue.data.html_url%'

  - title: Merge pull request
    description: Merge the pull request once I've approved it
    event: pull_request.closed
    link: '{{ repoUrl }}/pull/5'
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
      - type: createIssue
        title: You did it!
        body: 08_final-issue.md
        action_id: finalIssue
      - type: respond
        with: 08_comment-final-pr.md
        data:
          url: '%actions.finalIssue.data.html_url%'
