title: Revisando solicitudes de extracción
description: See how collaboration works on GitHub and start building great things, together.
tags:
  - GitHub
template:
  name: revisar-pull-request
  repo: revisar-pull-request-plantilla
before:
  - type: updateBranchProtection
  - type: createIssue
    title: Welcome
    body: 01_intro.md
steps:
  - title: Asígnate
    description: Asígnate a ti misma a la primera propuesta en este repositorio.
    event: issues.assigned
    link: "{{ repoUrl }}/issues/1"
    actions:
      - type: gate
        left: "%payload.assignee.login%"
        operator: ===
        right: "%user.username%"
      - type: createPullRequest
        title: Actualiza las instrucciones del juego
        body: 02_review-101.md
        head: game-instructions
        action_id: pr2
      - type: requestReviewFromRegistrant
        pullRequest: "%actions.pr2.data.number%"
      - type: respond
        with: 02_close-first-issue.md
        data:
          url: "%actions.pr2.data.html_url%"
      - type: closeIssue
        issue: Welcome

  - title: Comenta en una solicitud de extracción
    description: Crea un comentario en la solicitud de extracción añadida a tu repositorio.
    event: pull_request_review.submitted
    link: "{{ repoUrl }}/pull/2"
    actions:
      - type: gate
        every: true
        gates:
          - left: "%payload.review.state%"
            operator: ===
            right: "commented"
          - left: "%payload.pull_request.title%"
            operator: ===
            right: Actualiza las instrucciones del juego
        else:
          - type: respond
            with: error.md
      - type: respond
        with: 03_successful-comment.md

  - title: Aprueba la solicitud de extracción.
    description: Aprueba la solicitud de extracción para que pueda ser fusionada.
    event: pull_request_review.submitted
    link: "{{ repoUrl }}/pull/2"
    actions:
      - type: gate
        left: "%payload.review.state%"
        operator: ===
        right: "approved"
      - type: mergeBranch
        head: game-instructions
      - type: deleteBranch
        branch: game-instructions
      - type: createPullRequest
        title: Cambia los colores del tetris
        body: 04_requesting-changes.md
        head: update-colors
        action_id: pr3
      - type: respond
        with: 04_merging-pull-request.md
        data:
          url: "%actions.pr3.data.html_url%"

  - title: Solicita cambios
    description: Deja una revisión que solicite algunos cambios.
    event: pull_request_review.submitted
    link: "{{ repoUrl }}/pull/3"
    actions:
      - type: gate
        left: "%payload.review.state%"
        operator: ===
        right: "changes_requested"
        else:
          - type: gate
            left: "%payload.review.state%"
            operator: ===
            right: commented
            else:
              - type: gate
                left: "%payload.review.state%"
                operator: ===
                right: approved
              - type: respond
                with: 05_approval.md
          - type: respond
            with: 05_general-comment.md
      - type: mergeBranch
        head: add-multiple-colors
        base: update-colors
      - type: deleteBranch
        branch: add-multiple-colors
      - type: respond
        with: 05_changes-requested.md

  - title: Practica revisiones
    description: Aprueba la solicitud de extracción después de que haya sido modificada.
    event: pull_request_review.submitted
    link: "{{ repoUrl }}/pull/3"
    actions:
      - type: gate
        left: "%payload.review.state%"
        operator: ===
        right: "approved"
      - type: mergePullRequest
      - type: deleteBranch
        branch: update-colors
      - type: respond
        with: 08-suggest.md
        data:
          url: "%payload.repository.html_url%/compare/update-readme?expand=1"

  - title: Abre una solicitud de extracción desde readme-update
    description: Crea una solicitud de extracción para aprender acerca de cómo sugerir cambios.
    event: pull_request
    link: "{{ repoUrl }}/compare/readme-update?expand=1"
    actions:
      - type: gate
        gates:
          - left: "%payload.action%"
            operator: "==="
            right: "opened"
          - left: "%payload.action%"
            operator: "==="
            right: "edited"
      - type: gate
        left: "%payload.pull_request.body%"
        else:
          type: respond
          with: fix-body.md
      - type: createPullRequestComment
        file: README.md
        body: 08-suggest-pr.md
        position: 5
        data:
          # !! We don't ask the learner to turn on pages, so this is just a guess and won't translate to GHES
          pagesUrl: https://%user.username%.github.io/github-games/

  - title: Aplica la sugerencia
    description: Implementa un cambio desde una sugerencia de cambio.
    event: pull_request.synchronize
    link: "{{ repoUrl }}/pulls"
    actions:
      - type: createReview
        event: APPROVE
        body: 08-suggest-merge.md

  - title: Fusiona la solicitud de extracción
    description: Fusiona la solicitud de extracción despúes de aplicar el cambio sugerido.
    event: pull_request.closed
    link: "{{ repoUrl }}/pulls"
    actions:
      - type: gate
        left: "%payload.pull_request.merged%"
        else:
          - type: respond
            with: 08_accidental-close.md
      - type: respond
        with: 08_final-issue.md
