title: Reviewing Pull Requests
tagline: Start collaborating for GitHub, with GitHub.
description: Learn how GitHub uses pull request reviews to communicate and collaborate during the development process.
template:
    name: reviewing-pull-requests
    url: https://github.com/githubtraining/review-pull-requests-template.git
before:
  - type: updateBranchProtection
  - type: createIssue
    title: Welcome
    body: 01_intro.md
steps:
  - title: Assign Yourself
    description: Assign yourself to the first issue in this repository
    event: issues.assigned
    link: https://github.com/{{ course.Organization.login }}/{{ registration.repositoryName }}/issues/1
    actions:
      - type: gate
        left: "%payload.assignee.login%"
        operator: "==="
        right: "%user.username%"
      - type: respond
        with: 02_close-first-issue.md
      - type: createPullRequest
        title: Update Game Instructions
        body: 02_review-101.md
        head: game-instructions

  - title: Comment on a pull request
    description: Comment on the pull request opened in your repository.
    event: pull_request_review.submitted
    link: https://github.com/{{ course.Organization.login }}/{{ registration.repositoryName }}/pull/2
    actions:
      - type: gate
        left: '%payload.review.state%'
        operator: ===
        right: 'commented'
        # TODO check this, make sure that user has commented on the proper PR
      - type: respond
        with: 03_successful-comment.md

  - title: Approve a pull request
    description: Approve the pull request so that it can be merged.
    event: pull_request_review.submitted
    link: https://github.com/{{ course.Organization.login }}/{{ registration.repositoryName }}/pull/2
    actions:
      - type: gate
        left: '%payload.review.state%'
        operator: ===
        right: 'approved'
      - type: mergeBranch
        head: game-instructions
      - type: respond
        with: 04_merging-pull-request.md
      - type: createPullRequest
        title: Change Tetris Colors
        body: 04_requiring-changes.md
        head: update-colors

  - title: Requesting Changes
    description: Leave a review that is requesting changes.
    event: pull_request_review.submitted
    link: https://github.com/{{ course.Organization.login }}/{{ registration.repositoryName }}/pull/3
    actions:
      - type: gate
        left: '%payload.review.state%'
        operator: ===
        right: 'changes_requested'
        else:
        - type: gate
          gates:
            - left: '%payload.review.state'
              operator: ===
              right: COMMENT
            - type: respond
              with: 05_general-comment.md
            - left: '%payload.review.state'
              operator: ===
              right: APPROVE
            - type: respond
              with: 05_approval.md
      - type: mergeBranch
        head: add-multiple-colors
        base: update-colors
      - type: respond
        with: 05_changes-requested.md
  #     - type: # TODO change the branch in the pull request to reflect the requested changes

  - title: Approve another pull request
    description: Approve the pull request that has been changed
    event: pull_request_review.submitted
    link: https://github.com/{{ course.Organization.login }}/{{ registration.repositoryName }}/pull/3
    actions:
      - type: gate
        left: '%payload.review.state%'
        operator: ===
        right: 'approved'
      - type: respond
        with: 06_thanks-for-approval.md
      - type: mergePullRequest
      - type: createIssue
        title: The Final Review
        body: 06_final-flow.md
        data:
          url: 'https://%user.username%.github.io/%payload.repository.name%'

  - title: Request a reviewer
    description: Create a new pull request, and request that the Lab Bot reviews it.
    event: pull_request.opened
    link: https://github.com/{{ course.Organization.login }}/{{ registration.repositoryName }}/pull/5
    actions:
      - type: createReview
        body: 07_approve-pr.md
        event: APPROVE
      - type: closeIssue
        issue: The Final Review
      - type: respond
        issue: The Final Review
        with: 07_close-issue.md
        data:
          # TODO check if URL below is correct
          url: '%actions.issue.data.html_url%'

  - title: Merge pull request
    description: Merge the pull request once I've approved it.
    event: pull_request.closed
    link: https://github.com/{{ course.Organization.login }}/{{ registration.repositoryName }}/pull/5
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
      - type: respond
        with: 08_comment-final-pr.md
      - type: createIssue
        title: You did it!
        body: 08_final-issue.md
