title: Reviewing pull requests
tagline: Improve your collaboration on GitHub with pull request reviews.
description: See how collaboration works on GitHub and start building great things, together.
tags:
  - GitHub
template:
  name: reviewing-a-pull-request
  repo: reviewing-a-pull-request-template
before:
  - type: updateBranchProtection
  - type: createIssue
    title: Welcome
    body: 01_intro.md
steps:
  - title: Assign Yourself
    description: Assign yourself to the first issue in this repository.
    event: issues.assigned
    link: "{{ repoUrl }}/issues/1"
    actions:
      - type: gate
        left: "%payload.assignee.login%"
        operator: ===
        right: "%user.username%"
      - type: createPullRequest
        title: Update Game Instructions
        body: 02_review-101.md
        head: game-instructions
        action_id: pr2
      - type: requestReviewFromRegistrant
        pullRequest: "%actions.pr2.data.number%"
      - type: respond
        with: 02_close-first-issue.md
        data:
          url: "%actions.pr2.data.html_url%"
      - type: closeIssue
        issue: Welcome

  - title: Comment on a pull request
    description: Comment on the pull request opened in your repository.
    event: pull_request_review.submitted
    link: "{{ repoUrl }}/pull/2"
    actions:
      - type: gate
        every: true
        gates:
          - left: "%payload.review.state%"
            operator: ===
            right: "commented"
          - left: "%payload.pull_request.title%"
            operator: ===
            right: Update Game Instructions
        else:
          - type: respond
            with: error.md
      - type: respond
        with: 03_successful-comment.md

  - title: Approve a pull request
    description: Approve the pull request so that it can be merged.
    event: pull_request_review.submitted
    link: "{{ repoUrl }}/pull/2"
    actions:
      - type: gate
        left: "%payload.review.state%"
        operator: ===
        right: "approved"
      - type: mergeBranch
        head: game-instructions
      - type: deleteBranch
        branch: game-instructions
      - type: createPullRequest
        title: Change Tetris Colors
        body: 04_requesting-changes.md
        head: update-colors
        action_id: pr3
      - type: respond
        with: 04_merging-pull-request.md
        data:
          url: "%actions.pr3.data.html_url%"

  - title: Requesting changes
    description: Leave a review that is requesting changes.
    event: pull_request_review.submitted
    link: "{{ repoUrl }}/pull/3"
    actions:
      - type: gate
        left: "%payload.review.state%"
        operator: ===
        right: "changes_requested"
        else:
          - type: gate
            left: "%payload.review.state%"
            operator: ===
            right: commented
            else:
              - type: gate
                left: "%payload.review.state%"
                operator: ===
                right: approved
              - type: respond
                with: 05_approval.md
          - type: respond
            with: 05_general-comment.md
      - type: mergeBranch
        head: add-multiple-colors
        base: update-colors
      - type: deleteBranch
        branch: add-multiple-colors
      - type: respond
        with: 05_changes-requested.md

  - title: Practice reviews
    description: Approve the pull request that has been changed.
    event: pull_request_review.submitted
    link: "{{ repoUrl }}/pull/3"
    actions:
      - type: gate
        left: "%payload.review.state%"
        operator: ===
        right: "approved"
      - type: mergePullRequest
      - type: deleteBranch
        branch: update-colors
      - type: respond
        with: 08-suggest.md
        data:
          url: "%payload.repository.html_url%/compare/update-readme?expand=1"

  - title: Open a pull request from readme-update
    description: Create a pull request to learn about suggesting changes.
    event: pull_request
    link: "{{ repoUrl }}/compare/readme-update?expand=1"
    actions:
      - type: gate
        gates:
          - left: "%payload.action%"
            operator: "==="
            right: "opened"
          - left: "%payload.action%"
            operator: "==="
            right: "edited"
      - type: gate
        left: "%payload.pull_request.body%"
        else:
          type: respond
          with: fix-body.md
      - type: createPullRequestComment
        file: README.md
        body: 08-suggest-pr.md
        position: 5
        data:
          # !! We don't ask the learner to turn on pages, so this is just a guess and won't translate to GHES
          pagesUrl: https://%user.username%.github.io/github-games/

  - title: Apply the suggestion
    description: Implement a change from a suggested change.
    event: pull_request.synchronize
    link: "{{ repoUrl }}/pulls"
    actions:
      - type: createReview
        event: APPROVE
        body: 08-suggest-merge.md

  - title: Merge the pull request
    description: Merge the pull request after applying the suggested change.
    event: pull_request.closed
    link: "{{ repoUrl }}/pulls"
    actions:
      - type: gate
        left: "%payload.pull_request.merged%"
        else:
          - type: respond
            with: 08_accidental-close.md
      - type: respond
        with: 08_final-issue.md
